version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "com-acloudguru-play-store-event-emitter"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13fmezeefy2ud"
s3_prefix = "com-acloudguru-play-store-event-emitter"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "PackageNameParameter=\"com.acloudguru\""

