version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "play-store-event-emitter-sam"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mn6rqwb47fbw"
s3_prefix = "play-store-event-emitter-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

