# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  play-store-event-emitter

Transform:
  - AWS::Serverless-2016-10-31

Resources:
  PlayStoreEventEmitterConfigurationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "play-store-event-emitter-${AWS::Region}-${AWS::AccountId}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    DeletionPolicy: Delete

  ScheduledEventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that polls the configured Play Store app to watch for latest updates
      Runtime: nodejs12.x
      CodeUri: ./dist
      Handler: handlers/scheduled-event-logger.scheduledEventLoggerHandler
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Name: PlayStore-app-poll-rate
            Schedule: rate(1 hour)
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables:
          ConfigurationBucketName: !Ref PlayStoreEventEmitterConfigurationBucket
          PackageName: com.sampsonjoliver.acgpwa
          ReleaseRepositoryTableName: !Ref ReleaseRepositoryTable
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref PlayStoreEventEmitterConfigurationBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ReleaseRepositoryTable

  ReleaseRepositoryTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: play-store-event-emitter-app-track-releases
      PrimaryKey:
        Name: releaseTrack
        Type: String
