# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  play-store-event-emitter

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  PackageNameParameter:
    Type: String
    Description: Yhe package name of the android application to observes

Resources:
  ScheduledEventLogger:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that polls the configured Play Store app to watch for latest updates
      Runtime: nodejs12.x
      CodeUri: ./dist
      Handler: handlers/scheduled-event-logger.scheduledEventLoggerHandler
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Name: PlayStore-app-poll-rate
            Schedule: rate(1 hour)
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables:
          ConfigurationBucketName: !Ref PlayStoreEventEmitterConfigurationBucket
          PackageName:
            Ref: PackageNameParameter
          ReleaseRepositoryTableName: !Ref ReleaseRepositoryTable
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref PlayStoreEventEmitterConfigurationBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ReleaseRepositoryTable

  ReleaseRepositoryTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub psee-${PackageNameParameter}-track-releases
      PrimaryKey:
        Name: releaseId
        Type: String
        Default: com.sampsonjoliver.acgpwa

  PlayStoreEventEmitterConfigurationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "psee-${PackageNameParameter}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    DeletionPolicy: Delete
