# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

AWSTemplateFormatVersion: 2010-09-09
Description: >-
  play-store-event-emitter

Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  PackageNameParameter:
    Type: String
    Description: The package name of the android application to observes

Resources:
  PlayStoreReleasesEventBus:
    Type: "AWS::Events::EventBus"
    Properties:
      Name: PlayStoreReleasesEventBus

  PlayStoreObserverHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: A Lambda function that polls the configured Play Store app to watch for latest updates
      Runtime: nodejs12.x
      CodeUri: ./dist
      Handler: handlers/PlayStoreObserverHandler.handler
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Name: PlayStore-app-poll-rate
            Schedule: rate(1 hour)
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables:
          ConfigurationBucketName: !Ref PlayStoreEventEmitterConfigurationBucket
          PackageName:
            Ref: PackageNameParameter
          ReleaseSnapshotsTableName: !Ref ReleaseSnapshotsTable
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref PlayStoreEventEmitterConfigurationBucket
        - DynamoDBCrudPolicy:
            TableName: !Ref ReleaseSnapshotsTable

  ReleaseEventEmitterHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: Sends an event to a configured subscriber when a new release update is received
      Runtime: nodejs12.x
      CodeUri: ./dist
      Handler: handlers/ReleaseEventEmitterHandler.handler
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt ReleaseSnapshotsTable.StreamArn
            BatchSize: 5
            StartingPosition: TRIM_HORIZON
      Policies: AWSLambdaDynamoDBExecutionRole
      MemorySize: 128
      Timeout: 100
      Environment:
        Variables:
          EventBusName: !Ref PlayStoreReleasesEventBus
      Policies:
        - EventBridgePutEventsPolicy:
            EventBusName: !Ref PlayStoreReleasesEventBus


  ReleaseSnapshotsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub psee-${PackageNameParameter}-track-releases
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: releaseId
          AttributeType: S
      KeySchema:
        - AttributeName: releaseId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  PlayStoreEventEmitterConfigurationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "psee-${PackageNameParameter}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
    DeletionPolicy: Delete
